name: Linting, Testing and Building
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
permissions:
    contents: write
    pages: write
    id-token: write
concurrency:
    group: 'pages'
    cancel-in-progress: true
jobs:
    pipeline:
        runs-on: windows-latest
        concurrency: ci-${{ github.ref }}
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        strategy:
            matrix:
                node-version: [18.x]
        steps:
            - uses: actions/checkout@v2
            - name: Staring Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: install modules
              run: npm ci
            - name: build production project
              run: npm run build:prod
              if: always()
            - name: linting typescript
              run: npm run lint
              if: always()
            - name: linting css
              run: npm run style
              if: always()
            - name: unit testing
              run: npm run unit
              if: always()
            - name: Setup Pages
              uses: actions/configure-pages@v2
              if: always()
            - name: Deploy to GitHub Pages
              id: deployment
              if: always()
              uses: actions/deploy-pages@v1
