name: Linting, Testing and Building
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    pipeline:
        runs-on: windows-latest
        strategy:
            matrix:
                node-version: [17.x]
        steps:
            - uses: actions/checkout@v2
            - name: Staring Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: install modules
              run: npm install
            - name: build production project
              run: npm run build:prod
              if: always()
            - name: linting typescript
              run: npm run lint
              if: always()
            - name: linting css
              run: npm run style
              if: always()
            - name: unit testing
              run: npm run unit
              if: always()
